title: JournalHub API Documentation
description: Comprehensive documentation for the JournalHub API
theme: jekyll-theme-cayman

# Navigation
nav:
  - title: Introduction
    url: /docs/introduction
  - title: Authentication
    url: /docs/authentication
  - title: User Management
    url: /docs/user-management
  - title: Journal Entries
    url: /docs/journal-entries
  - title: Error Handling
    url: /docs/error-handling
  - title: Rate Limiting
    url: /docs/rate-limiting
  - title: Security
    url: /docs/security
  - title: Architecture
    url: /docs/architecture
  - title: Database
    url: /docs/database
  - title: Examples
    url: /docs/examples
  - title: Code Samples
    url: /docs/code-samples
  - title: Changelog
    url: /docs/changelog
  - title: Glossary
    url: /docs/glossary
